name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Building bd plugin (ubuntu only since it's not platform dependent)
        if: matrix.platform == 'ubuntu-20.04'
        run: pnpm run bundlebd:build

      - uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build
        env:
          TAURI_KEY_PASSWORD: ''

      - uses: actions/upload-artifact@v3
        with:
          name: "artifacts-${{ matrix.platform }}"
          path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}\n./dist-bd/DiscordSourcePlugin.plugin.js"
