name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v2.1.1

      - name: Unzip all artifacts
        uses: montudor/action-zip@v1
        with:
          args: unzip *.zip -d unzipped_artifacts
          
      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "unzipped_artifacts/**/*"
          draft: true
