name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Sync node version
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'pnpm'

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Update version
        run: pnpm run setVersion ${{ github.event.inputs.tag }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'release: ${{ github.event.inputs.tag }}'
          labels: 'release'
          reviewers: 'Dreaming-Codes'
          title: 'release: ${{ github.event.inputs.tag }}'
          body: ''
          base: 'master'
          branch: 'release/${{ github.event.inputs.tag }}'
